# Verification of Answers to Problems 1

## Foreward Kinematics


Using the values from question 1 part A: The joint angles **$\theta$** are given by 

$$
\theta = \begin{bmatrix} \theta_1 \\ \theta_2 \end{bmatrix} = \begin{bmatrix} 5\pi/6 \\ -3\pi/7 \end{bmatrix}
$$

Using the forward kinematic equations we derived from question 1 we find that the transformation matrix from C to 0 is:

$$
{}^0T_C =
\begin{bmatrix}
-0.5   & -0.1927 & 0.8443 & 1.0754 \\
-0.8660& 0.1113  & -0.4875& 0.3028 \\
0      & -0.9749 & -0.2225& 1.0220 \\
0      & 0       & 0      & 1.0
\end{bmatrix}
$$

The quaternion is: 0.3117 < -0.3909,  0.6771, -0.5400 >

Now, using Mujoco we can plug in these **$\theta$** values and see that the transformation (and quaternion) is the same. 




In [100]:
import mujoco as mj
import mujoco.viewer
import time
import numpy as np
import sympy as sp

# Load the XML model

model = mj.MjModel.from_xml_path("penulum.xml")

data = mj.MjData(model)

joint1_name = "joint1"
joint2_name = "joint2"

joint1_id = model.joint(joint1_name).id
joint2_id = model.joint(joint2_name).id



world_frame_id = 0


frame1_name = "frame1"
frame1_id = model.body(name=frame1_name).id


frame2_name = "frame2"
frame2_id = model.body(name=frame2_name).id

end_effector_body_name="end-effector"
end_effector_body_id = model.body(name=end_effector_body_name).id


theta1_parta = 5 * np.pi / 6
theta2_parta = -3 * np.pi / 7

#set model to the given theta values
data.qpos[joint1_id] = theta1_parta
data.qpos[joint2_id] = theta2_parta

mj.mj_forward(model, data)

def get_spatial_transformation(body_id):
    #Extract the positions
    rot = data.xmat[body_id].reshape(3,3)
    pos = data.xpos[body_id]


    #Convert to transformation matrix
    transformation = np.eye(4) 
    transformation[:3, :3] = rot  
    transformation[:3, 3] = pos 
    return transformation

def quat_print(quat):
    """
    Prints a quaternion in the format: <w, <x, y, z>>
    AI Generated function
    
    Args:
        quat (list or tuple): A quaternion [w, x, y, z]
    """
    if len(quat) != 4:
        raise ValueError("Quaternion must be a list or tuple of 4 elements [w, x, y, z]")
    
    w, x, y, z = [round(val, 4) for val in quat]

    print(f"{w}, <{x}, {y}, {z}>")




#Display
quat_print(data.xquat[end_effector_body_id])
sp.Matrix(np.round(get_spatial_transformation(end_effector_body_id), 4))


0.3117, <-0.3909, 0.6771, -0.54>


Matrix([
[  -0.5, -0.1927,  0.8443, 1.0754],
[-0.866,  0.1113, -0.4875, 0.3028],
[   0.0, -0.9749, -0.2225,  1.022],
[   0.0,     0.0,     0.0,    1.0]])

## Inverse Kinematics

In Question 1d we are asked to find the values of theta corresponding to a given orientation of the camera frame. To verify this calculation we can plug in the values of theta that we found and see if the orientation matches what was given. 


The values of theta we found are:

$$
\left[\begin{matrix}-45.0 & 315.0\\135.0 & 45.0\end{matrix}\right]
$$
 Where each row is one of two possible solutions. Columns 1 and 2 represet **theta1** and **theta2** respectivly.


The expected result is:

$$
k = -\frac{1}{2} x_0 + \frac{1}{2} y_0 - \frac{\sqrt{2}}{2} z_0.
$$

In [101]:
solutions = [(-0.785398163397448, 5.49778714378214),
 (0.785398163397448, 0.785398163397448),
 (2.35619449019234, 0.785398163397448),
 (3.92699081698724, 5.49778714378214)]


theta1_sol1_partd = np.deg2rad(-45)
theta2_sol1_partd = np.deg2rad(135)

theta1_sol2_partd = np.deg2rad(315)
theta2_sol2_partd = np.deg2rad(45)

print("Expected: \n[-0.5         0.5        -0.70710678]\nActual:\n")

for solution in solutions:
    #set model to solution
    data.qpos[joint1_id] = solution[0]
    data.qpos[joint2_id] = solution[1]
    mj.mj_forward(model, data)
    
    k = data.xmat[end_effector_body_id].reshape(3,3)[:,2]
    print(k)

    print()

Expected: 
[-0.5         0.5        -0.70710678]
Actual:

[-0.5         0.5        -0.70710678]

[ 0.5         0.5        -0.70710678]

[-0.5         0.5        -0.70710678]

[ 0.5         0.5        -0.70710678]



As can be seen above, two of the solutions match the given K vector and two do not, which is exactly what was expected. 


# Verification of answers to Problem 2

#### Part A

Using the values from question 1 part A: The joint angles **$\theta$** are given by 

$$
\theta = \begin{bmatrix} \theta_1 \\ \theta_2 \end{bmatrix} = \begin{bmatrix} 5\pi/6 \\ -3\pi/7 \end{bmatrix}
$$

The angular rates of change are also given:

$$
\dot{\boldsymbol{\theta}} = \begin{bmatrix} 1 & 2 \end{bmatrix}^{\top}
$$ 



The goal is to find the spatial and body twist, the spatial twist  found was:

$$
\begin{bmatrix}
-2.07846096908265 \\
1.2 \\
0 \\
1.0 \\
1.73205080756888 \\
1.0
\end{bmatrix}
$$

The body twist was: 

$$
\left[\begin{matrix}-0.779942329745459\\1.77801674716505\\-0.779942329745459\\-2.0\\-0.974927912181824\\-0.222520933956314\end{matrix}\right]
$$


In [112]:
# --- Reset the simulation and set the configuration ---
mj.mj_resetData(model, data)

# Joint angles (from Question 1 Part A)
theta1_parta = 5 * np.pi / 6
theta2_parta = -3 * np.pi / 7

# Set joint positions
data.qpos[joint1_id] = theta1_parta
data.qpos[joint2_id] = theta2_parta

# Set joint velocities: [1.0, 2.0]
data.qvel[joint1_id] = 1.0
data.qvel[joint2_id] = 2.0

# Compute the forward dynamics to update the simulation state
mj.mj_forward(model, data)

# --- Retrieve Sensor Data to Form the Twists ---

# Get sensor IDs for the new sensor names:
# Spatial sensors (world frame)
spatial_lin_sensor_id = model.sensor("spatial-linear-vel").id # 0
spatial_ang_sensor_id = model.sensor("spatial-ang-vel").id # 1

# Body sensors (end-effector's frame)
body_lin_sensor_id = model.sensor("body-linear-vel").id # 2
body_ang_sensor_id = model.sensor("body-ang-vel").id # 3

# Since each sensor returns a 3D vector, we slice 3 elements starting at each sensor's id.
# Note: sensor data is stored in a 1D array in sensor order.

# Spatial twist: measured in the world frame [linear; angular]
spatial_lin_vel = data.sensordata[0 : 3]
spatial_ang_vel = data.sensordata[3 : 6]
spatial_twist = np.concatenate([spatial_lin_vel, spatial_ang_vel])
print("Spatial Twist (linear; angular):")
print(spatial_twist)
# Expected spatial twist:
# [ -2.07846096908265, 1.2, 0, 1.0, 1.73205080756888, 1.0 ]

# Body twist: measured in the end-effector's (body) frame [linear; angular]
body_lin_vel = data.sensordata[6 : 9]
body_ang_vel = data.sensordata[9 : 12]
body_twist = np.concatenate([body_lin_vel, body_ang_vel])
print("\nBody Twist (linear; angular):")
print(body_twist)
# Expected body twist:
# [ -0.779942329745459, 1.77801674716505, -0.779942329745459,
#   -2.0, -0.974927912181824, -0.222520933956314 ]


Spatial Twist (linear; angular):
[-0.61118321  1.25346662 -1.55988466  1.          1.73205081  1.        ]

Body Twist (linear; angular):
[-0.77994233  1.77801675 -0.77994233 -2.         -0.97492791 -0.22252093]


In [ ]:
# # Do simulated runtime test

# import time
# import numpy as np
# import mujoco as mj

# # --- Reset the simulation and set the configuration ---
# mj.mj_resetData(model, data)

# # Joint angles (from Question 1 Part A)
# theta1_parta = 5 * np.pi / 6
# theta2_parta = -3 * np.pi / 7

# # Set joint positions (using joint indices defined earlier)
# data.qpos[joint1_id] = theta1_parta
# data.qpos[joint2_id] = theta2_parta

# # Set joint velocities: [1.0, 2.0]
# data.qvel[joint1_id] = 1.0
# data.qvel[joint2_id] = 2.0

# # Compute the forward dynamics to update the simulation state
# mj.mj_forward(model, data)

# # --- Debug: Print all valid sensor names ---
# sensor_names = [model.sensor(i).name for i in range(model.nsensor)]
# print("Valid sensor names:", sensor_names)
# print("Total sensors in model:", model.nsensor)

# # Get sensor IDs from the model:
# # Angular velocity sensors
# spatial_ang_sensor_id = model.sensor("spatial-ang-vel").id
# body_ang_sensor_id    = model.sensor("body-ang-vel").id

# # Linear velocity sensors (using framelinvel, as updated in your XML)
# spatial_lin_sensor_id = model.sensor("spatial-linear-vel").id
# body_lin_sensor_id    = model.sensor("body-linear-vel").id

# # If you prefer to use the joint sensors defined in your XML, you can also get their IDs:
# joint1_pos_sensor_id = model.sensor("joint1-position").id
# joint2_pos_sensor_id = model.sensor("joint2-position").id
# joint1_vel_sensor_id = model.sensor("joint1-velocity").id
# joint2_vel_sensor_id = model.sensor("joint2-velocity").id

# # --- Launch the viewer and print sensor data in real time ---
# with mj.viewer.launch_passive(model, data) as viewer:
#     print("Viewer launched. Press ESC to close.")
#     while viewer.is_running():
#         mj.mj_step(model, data)
#         viewer.sync()  # Refresh the visualization
#         time.sleep(0.001)  # Adjust the sleep time as needed

#         # Retrieve sensor outputs:
#         spatial_ang_vel = data.sensordata[spatial_ang_sensor_id : spatial_ang_sensor_id + 3]
#         spatial_lin_vel = data.sensordata[spatial_lin_sensor_id : spatial_lin_sensor_id + 3]
#         body_ang_vel    = data.sensordata[body_ang_sensor_id    : body_ang_sensor_id    + 3]
#         body_lin_vel    = data.sensordata[body_lin_sensor_id    : body_lin_sensor_id    + 3]

#         # Print spatial and body velocities:
#         print("Spatial Angular Velocity:", spatial_ang_vel)
#         print("Spatial Linear  Velocity:", spatial_lin_vel)
#         print("Body Angular    Velocity:", body_ang_vel)
#         print("Body Linear     Velocity:", body_lin_vel)

#         # Print joint positions and velocities (directly from data.qpos and data.qvel)
#         joint_positions = [data.qpos[joint1_id], data.qpos[joint2_id]]
#         joint_velocities = [data.qvel[joint1_id], data.qvel[joint2_id]]
#         print("Joint Positions:", joint_positions)
#         print("Joint Velocities:", joint_velocities)
#         print("-" * 50)


Valid sensor names: ['spatial-linear-vel', 'spatial-ang-vel', 'body-linear-vel', 'body-ang-vel', 'joint1-position', 'joint2-position', 'joint1-velocity', 'joint2-velocity']
Total sensors in model: 8
Viewer launched. Press ESC to close.
Spatial Angular Velocity: [ 1.25346662 -1.55988466  1.        ]
Spatial Linear  Velocity: [-0.61118321  1.25346662 -1.55988466]
Body Angular    Velocity: [1.         1.73205081 1.        ]
Body Linear     Velocity: [-1.55988466  1.          1.73205081]
Joint Positions: [np.float64(2.6199864854865256), np.float64(-1.3423721574847833)]
Joint Velocities: [np.float64(0.9917672824589305), np.float64(2.0248807775195963)]
--------------------------------------------------
Spatial Angular Velocity: [ 1.24814848 -1.57782669  1.00894415]
Spatial Linear  Velocity: [-0.6208745   1.24814848 -1.57782669]
Body Angular    Velocity: [1.00894415 1.75561211 0.99176728]
Body Linear     Velocity: [-1.57782669  1.00894415  1.75561211]
Joint Positions: [np.float64(2.6219619523

KeyboardInterrupt: 